
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guebnnhdjvdhjqescpeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZWJubmhkanZkaGpxZXNjcGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDgxNTYsImV4cCI6MjA1ODEyNDE1Nn0.ddem8_jTEW7EAfDxcwmqbZ8TgvQpGbtjJwmlDtW2_YU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Since the types file might not immediately reflect the new appointments table,
// we'll create a custom client with any to prevent TypeScript errors
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper for typecasting tables
export type Tables = Database['public']['Tables'];
